name: Validate Branch Name

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  validate-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Branch Naming Convention
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ ! "$BRANCH_NAME" =~ ^[A-Za-z\-]+-[A-Za-z\-]+-sprint[0-9]+$ ]]; then
            echo "Error: Branch name '$BRANCH_NAME' does not follow the required naming convention."
            echo "Expected format: pr-check-branch-name-yihao-sprint6"
            exit 1
          fi
